initial_velocity = 50;    
launch_angle = 45;        
g = 9.81;                 
theta = deg2rad(launch_angle);
v_x = initial_velocity * cos(theta);
v_y = initial_velocity * sin(theta); 
time_of_flight = (2 * v_y) / g;
t = linspace(0, time_of_flight, 100);
x = v_x * t;                        
range = max(x);                    
max_height = (v_y^2) / (2 * g);    
figure;
plot(x, y, 'b-', 'LineWidth', 2);
hold on;
plot(range, 0, 'ro', 'MarkerSize', 8, 'MarkerFaceColor', 'r'); 
plot(0, max_height, 'go', 'MarkerSize', 8, 'MarkerFaceColor', 'g'); 
xlabel('Horizontal Distance (m)');
ylabel('Vertical Distance (m)');
title('Projectile Trajectory');
legend('Trajectory', 'Range', 'Max Height');
grid on;
fprintf('Range: %.2f meters\n', range);
fprintf('Maximum Height: %.2f meters\n', max_height);
